services:
  - type: web
    name: clinton-county-gis
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python data_prep.py
    startCommand: gunicorn app:app --timeout 120 --workers 2
